apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000  
    nodePort: 30001 